// <auto-generated />
using System;
using ChallengeCore.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ChallengeCore.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ChallengeCore.Domain.Entity.Challenge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsBonus")
                        .HasColumnType("bit");

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Challenges");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4ed83a3c-6207-4996-b68d-973e2eb1d877"),
                            Description = "Verifica que tu información personal esté completa.",
                            IsBonus = false,
                            Points = 10,
                            Title = "Completa tu perfil",
                            Type = "simple"
                        },
                        new
                        {
                            Id = new Guid("d3312eba-aeca-4721-a8b3-80bccc312409"),
                            Description = "Ingresa el monto objetivo de ahorro mensual.",
                            IsBonus = false,
                            Points = 20,
                            Title = "Configura una meta de ahorro",
                            Type = "experto"
                        },
                        new
                        {
                            Id = new Guid("2456a3c7-fcbf-48b8-8023-bc71e4888318"),
                            Description = "Elige entre las opciones de inversión disponibles.",
                            IsBonus = false,
                            Points = 15,
                            Title = "Selecciona tu tipo de inversión",
                            Type = "seleccion"
                        },
                        new
                        {
                            Id = new Guid("5c3f088a-3acd-4363-870a-44b9f62e3e21"),
                            Description = "Realiza una simulación básica de préstamo.",
                            IsBonus = false,
                            Points = 25,
                            Title = "Simula un préstamo",
                            Type = "simple"
                        },
                        new
                        {
                            Id = new Guid("55c567c9-3ec6-4540-92e3-db6ab334f9b4"),
                            Description = "Completa el módulo básico de educación financiera.",
                            IsBonus = true,
                            Points = 100,
                            Title = "Reto Premium: Educación Financiera",
                            Type = "simple"
                        });
                });

            modelBuilder.Entity("ChallengeCore.Domain.Entity.Reward", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Cost")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Rewards");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c57756f1-6b85-40f5-a102-0f78ba7c0ee2"),
                            Cost = 40,
                            Description = "Obtén $5 de devolución en tu próxima compra.",
                            Name = "Cashback $5"
                        },
                        new
                        {
                            Id = new Guid("6170ca53-1b3a-4f3f-b4c7-9f6cd09f860e"),
                            Cost = 70,
                            Description = "Tarjeta de regalo digital de $10.",
                            Name = "Gift Card Digital $10"
                        },
                        new
                        {
                            Id = new Guid("9f0f3f61-58db-4d70-8c4a-6b1b7b4df111"),
                            Cost = 120,
                            Description = "Acceso a beneficios premium durante 30 días.",
                            Name = "Acceso Premium 1 Mes"
                        });
                });

            modelBuilder.Entity("ChallengeCore.Domain.Entity.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AvatarUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ChallengeCore.Domain.Entity.UserChallenge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid>("ChallengeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ChallengeId");

                    b.HasIndex("UserId");

                    b.ToTable("UserChallenges");
                });

            modelBuilder.Entity("ChallengeCore.Domain.Entity.UserReward", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("RedeemedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("RewardId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RewardId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRewards");
                });

            modelBuilder.Entity("ChallengeCore.Domain.Entity.UserChallenge", b =>
                {
                    b.HasOne("ChallengeCore.Domain.Entity.Challenge", "Challenge")
                        .WithMany("UserChallenges")
                        .HasForeignKey("ChallengeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ChallengeCore.Domain.Entity.User", "User")
                        .WithMany("UserChallenges")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Challenge");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ChallengeCore.Domain.Entity.UserReward", b =>
                {
                    b.HasOne("ChallengeCore.Domain.Entity.Reward", "Reward")
                        .WithMany("UserRewards")
                        .HasForeignKey("RewardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ChallengeCore.Domain.Entity.User", "User")
                        .WithMany("UserRewards")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reward");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ChallengeCore.Domain.Entity.Challenge", b =>
                {
                    b.Navigation("UserChallenges");
                });

            modelBuilder.Entity("ChallengeCore.Domain.Entity.Reward", b =>
                {
                    b.Navigation("UserRewards");
                });

            modelBuilder.Entity("ChallengeCore.Domain.Entity.User", b =>
                {
                    b.Navigation("UserChallenges");

                    b.Navigation("UserRewards");
                });
#pragma warning restore 612, 618
        }
    }
}
